version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn -v
      - echo test started on `Date`
      - mvn clean test -Dheadless=$HEADLESS -Dtarget=$TARGET -DsuiteXmlFile="src\test\resources\runner\testng.xml"